# Generated by Django 5.2.13 on 2026-04-25 19:10

import django.utils.timezone
import signaling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=signaling.models.generate_session_code, help_text='Unique session code (format: XXX-XXX-XXX)', max_length=11, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for peer'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('expired', 'Expired')], default='waiting', max_length=15)),
                ('host_identifier', models.CharField(blank=True, default='', help_text='Hostname or IP of the host machine', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='signaling_s_code_a1a950_idx'), models.Index(fields=['status'], name='signaling_s_status_4c692b_idx')],
            },
        ),
    ]
