# Generated by Django 5.2.13 on 2026-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='alias',
            field=models.CharField(blank=True, help_text='Custom display name for the session', max_length=100, null=True),
        ),
    ]
