# Generated by Django 5.2.13 on 2026-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0002_session_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='host_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
